const DAYS=['周日','周一','周二','周三','周四','周五','周六'];
const STORAGE='keling-courses-v1';
const defaultCourses=[
  {id:'c1',name:'高等数学',day:1,time:'08:00',room:'教学楼 A203',advance:20},
  {id:'c2',name:'大学英语',day:1,time:'14:00',room:'博学楼 305',advance:20},
  {id:'c3',name:'计算机基础',day:3,time:'10:00',room:'实验楼 2-106',advance:20},
  {id:'c4',name:'体育',day:5,time:'15:30',room:'东操场',advance:20}
];
let courses=JSON.parse(localStorage.getItem(STORAGE)||'null')||defaultCourses;
let selectedDay=new Date().getDay(),alarmTimer=null,audioCtx=null,oscillators=[],deferredPrompt=null;
const $=s=>document.querySelector(s);
const save=()=>localStorage.setItem(STORAGE,JSON.stringify(courses));
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function nextOccurrence(c,base=new Date()){const d=new Date(base);const delta=(c.day-d.getDay()+7)%7;d.setDate(d.getDate()+delta);const [h,m]=c.time.split(':').map(Number);d.setHours(h,m,0,0);if(d<=base)d.setDate(d.getDate()+7);return d}
function getNext(){return courses.map(c=>({c,date:nextOccurrence(c)})).sort((a,b)=>a.date-b.date)[0]}
function renderNext(){const n=getNext();$('#todayLabel').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date());if(!n){$('#nextCourse').innerHTML='<div class="empty">添加一节课后，这里会显示倒计时</div>';return}const diff=n.date-Date.now(),hours=Math.floor(diff/36e5),mins=Math.floor((diff%36e5)/6e4);$('#nextCourse').innerHTML=`<div class="next-name">${esc(n.c.name)}</div><div class="next-time">${DAYS[n.c.day]} · ${n.c.time} 上课</div><div class="next-room">${esc(n.c.room||'教室待定')}</div><div class="countdown"><strong>${hours>0?hours+' 小时 ':''}${mins} 分钟</strong><span>后上课</span></div>`}
function renderTabs(){const tabs=$('#dayTabs');tabs.innerHTML=DAYS.slice(1).concat(DAYS[0]).map((d,i)=>{const day=i===6?0:i+1;return `<button class="day-tab ${day===selectedDay?'active':''}" data-day="${day}" role="tab" aria-selected="${day===selectedDay}">${d.replace('周','')}</button>`}).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedDay=+b.dataset.day;renderTabs();renderCourses()})}
function renderCourses(){const list=$('#courseList'),items=courses.filter(c=>c.day===selectedDay).sort((a,b)=>a.time.localeCompare(b.time));list.innerHTML=items.length?items.map(c=>`<article class="course-card"><div class="course-time">${c.time}</div><div class="course-info"><strong>${esc(c.name)}</strong><small>${esc(c.room||'教室待定')} · 提前 ${c.advance} 分钟</small></div><div class="course-actions"><button class="mini-btn edit" data-id="${c.id}" aria-label="编辑 ${esc(c.name)}">✎</button><button class="mini-btn delete" data-id="${c.id}" aria-label="删除 ${esc(c.name)}">×</button></div></article>`).join(''):'<div class="empty">这一天还没有课程<br>点击右上角添加</div>';list.querySelectorAll('.edit').forEach(b=>b.onclick=()=>openCourse(b.dataset.id));list.querySelectorAll('.delete').forEach(b=>b.onclick=()=>{courses=courses.filter(c=>c.id!==b.dataset.id);save();renderAll();toast('课程已删除')})}
function renderAll(){renderTabs();renderCourses();renderNext()}
function openCourse(id){const c=courses.find(x=>x.id===id);$('#dialogTitle').textContent=c?'编辑课程':'添加课程';$('#courseId').value=c?.id||'';$('#courseName').value=c?.name||'';$('#courseDay').value=c?.day??selectedDay;$('#courseTime').value=c?.time||'08:00';$('#courseRoom').value=c?.room||'';$('#courseAdvance').value=c?.advance||20;$('#courseDialog').showModal()}
function startSound(){stopSound();audioCtx=new(window.AudioContext||window.webkitAudioContext)();const ring=()=>{if(!audioCtx)return;[880,660].forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(0,audioCtx.currentTime);g.gain.linearRampToValueAtTime(.16,audioCtx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.38);o.connect(g).connect(audioCtx.destination);o.start(audioCtx.currentTime+i*.16);o.stop(audioCtx.currentTime+.42+i*.16);oscillators.push(o)});};ring();alarmTimer=setInterval(ring,1200)}
function stopSound(){clearInterval(alarmTimer);alarmTimer=null;oscillators.forEach(o=>{try{o.stop()}catch{}});oscillators=[];if(audioCtx){audioCtx.close();audioCtx=null}}
function fireAlarm(c){startSound();$('#alarmName').textContent=c.name;$('#alarmMeta').textContent=`${c.time} 上课${c.room?' · '+c.room:''}`;$('#alarmDialog').showModal();if(Notification.permission==='granted')navigator.serviceWorker?.ready.then(reg=>reg.showNotification(`还有 ${c.advance} 分钟上课`,{body:`${c.name}${c.room?' · '+c.room:''}`,icon:'icon.svg',tag:c.id}))}
let fired={};function checkAlarms(){const now=new Date();courses.forEach(c=>{const next=nextOccurrence(c,new Date(now.getTime()-8*24*36e5));const alarmAt=new Date(next.getTime()-c.advance*6e4);const key=c.id+'-'+next.toDateString();if(Math.abs(now-alarmAt)<30000&&!fired[key]){fired[key]=1;fireAlarm(c)}})}
function icsDate(d){return d.getFullYear()+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0')+'T'+String(d.getHours()).padStart(2,'0')+String(d.getMinutes()).padStart(2,'0')+'00'}
function exportCalendar(){if(!courses.length)return toast('请先添加课程');const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const events=courses.map(c=>{const start=nextOccurrence(c);const end=new Date(start.getTime()+90*6e4);return ['BEGIN:VEVENT',`UID:${c.id}@keling.app`,`DTSTAMP:${stamp}`,`DTSTART:${icsDate(start)}`,`DTEND:${icsDate(end)}`,'RRULE:FREQ=WEEKLY;COUNT=26',`SUMMARY:${c.name.replace(/[,;]/g,' ')}`,`LOCATION:${(c.room||'').replace(/[,;]/g,' ')}`,'BEGIN:VALARM',`TRIGGER:-PT${c.advance}M`,'ACTION:DISPLAY',`DESCRIPTION:${c.name}即将上课`,'END:VALARM','END:VEVENT'].join('\r\n')}).join('\r\n');const blob=new Blob(['BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Keling//Course Alarm//ZH\r\n'+events+'\r\nEND:VCALENDAR'],{type:'text/calendar;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='我的课表-提前20分钟提醒.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('课表已生成，请用系统日历打开')}
$('#courseDay').innerHTML=DAYS.map((d,i)=>`<option value="${i}">${d}</option>`).join('');
$('#addBtn').onclick=()=>openCourse();
$('#courseForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const id=$('#courseId').value||crypto.randomUUID();const c={id,name:$('#courseName').value.trim(),day:+$('#courseDay').value,time:$('#courseTime').value,room:$('#courseRoom').value.trim(),advance:+$('#courseAdvance').value};const idx=courses.findIndex(x=>x.id===id);idx<0?courses.push(c):courses.splice(idx,1,c);selectedDay=c.day;save();renderAll();$('#courseDialog').close();toast('课程已保存')});
$('#notifyBtn').onclick=async()=>{if(!('Notification'in window))return toast('当前浏览器不支持通知');const p=await Notification.requestPermission();$('#permissionNote').textContent=p==='granted'?'提醒已开启。保持 App 打开可响铃；导入日历后关闭也能提醒。':'通知未开启，请在浏览器设置中允许通知。';toast(p==='granted'?'提醒已开启':'未获得通知权限')};
$('#testBtn').onclick=()=>fireAlarm({id:'test',name:'铃声测试',time:'现在',room:'声音正常',advance:20});
$('#stopAlarmBtn').onclick=()=>{stopSound();$('#alarmDialog').close()};
$('#calendarBtn').onclick=exportCalendar;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').textContent='安装 App'});
$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else{$('#installDialog').showModal()}};
$('#closeInstallBtn').onclick=()=>$('#installDialog').close();
$('#gotItBtn').onclick=()=>$('#installDialog').close();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
function registerAgentTools(){const mc=document.modelContext;if(!mc?.registerTool)return;try{mc.registerTool({name:'list_courses',title:'查看课表',description:'读取当前课表中的全部课程。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({courses:[...courses].sort((a,b)=>a.day-b.day||a.time.localeCompare(b.time))})});mc.registerTool({name:'save_course',title:'保存课程',description:'添加或更新一节每周重复的课程，并同步更新页面。',inputSchema:{type:'object',properties:{id:{type:'string'},name:{type:'string'},day:{type:'integer',minimum:0,maximum:6},time:{type:'string',pattern:'^([01]\\d|2[0-3]):[0-5]\\d$'},room:{type:'string'},advance:{type:'integer',minimum:1,maximum:180}},required:['name','day','time','advance'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:i=>{if(!i.name.trim())throw new Error('课程名称不能为空');const c={id:i.id||crypto.randomUUID(),name:i.name.trim(),day:i.day,time:i.time,room:(i.room||'').trim(),advance:i.advance};const idx=courses.findIndex(x=>x.id===c.id);idx<0?courses.push(c):courses.splice(idx,1,c);selectedDay=c.day;save();renderAll();return{saved:true,course:c}}});}catch(e){console.warn('WebMCP registration unavailable',e)}}
registerAgentTools();
renderAll();setInterval(()=>{renderNext();checkAlarms()},15000);checkAlarms();

